name: Mirror to Private Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1) Clone completo do repo público
      - name: Checkout origin
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # preciso de todo histórico, branches e tags
          persist-credentials: false

      # 2) Configura usuário Git (opcional, mas recomendável para logs claros)
      - name: Setup Git author
        run: |
          git config user.name  "GitHub Actions Bot"
          git config user.email "actions@github.com"

      # 3) Adiciona o remote 'private' apontando para seu repo privado
      - name: Add private remote
        env:
          PAT: ${{ secrets.DEST_REPO_PAT }}
        run: |
          git remote add private https://x-access-token:${PAT}@github.com/freelaapp/freela-web-static-content.git

      # 4) Força o push de todas as refs (branches e tags)
      - name: Push to private
        run: |
          git push private +refs/heads/*:refs/heads/*    # espelha tudo
